apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        pullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}