apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  type: LoadBalancer
  selector:
    app: techtrends
  ports:
    name: http
    port: "{{ .Values.service.port }}"
    targetPort: "{{ .Values.service.targetPort }}"
    protocol: "{{ .Values.service.protocol }}"