apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  type: LoadBalancer
  ports:
  # port bên ngoài của pods mà các pods có thể giao tiếp được với nhau
  - port: 4111
  # port target với 8100 của deployment
    targetPort: 3111
    protocol: TCP
    name: http
  selector:
    app: techtrends    